#! /usr/bin/env ruby

#
# This is an inode agent which monitors
# disk INode usage
#

require "rubygems"
require "bundler/setup"
require "newrelic_plugin"

module INodeAgent
  class Agent < NewRelic::Plugin::Agent::Base

    agent_guid "com.datazoos.newrelic.plugins.inode_monitor"
    agent_version "1.0.1"
    agent_config_options :hostname
    agent_human_labels("Inode Agent") { "#{hostname}" }

    def poll_cycle
        start = `df -i`
        result = {}
        disks = start.lines
        disks.shift()
        disks.each { |line|
            line = line.split(/[ ][0-9%]+/)
            mountedAt = line[7].strip()
            mountedFrom = line[0].strip()

            diskUsage = `df -i #{mountedAt}`.lines[1].gsub(mountedFrom, "").gsub('%', "").split(/[ ]{1,}/)
            result[mountedFrom] = {
                "size" => diskUsage[1].strip(),
                "used" => diskUsage[2].strip(),
                "avail" => diskUsage[3].strip(),
                "capacity" => diskUsage[4].strip(),
                "iused" => diskUsage[5].strip(),
                "ifree" => diskUsage[6].strip(),
                "iused_pct" => diskUsage[7].strip(),
                "mounted_on" => diskUsage[8].strip(),
            }
        }

        result.each { | disk, metric |
            metric.each { | k, v|
                report_metric("iNodes/#{disk}/#{k}",  "#{k}", v)
            }
        }


    end

  end

  NewRelic::Plugin::Setup.install_agent :inode, INodeAgent

  NewRelic::Plugin::Run.setup_and_run

end
