#! /usr/bin/env ruby

#
# This is an inode agent which monitors
# disk INode usage
#

require "rubygems"
require "bundler/setup"
require "newrelic_plugin"

module INodeAgent
  class Agent < NewRelic::Plugin::Agent::Base

    agent_guid "com.datazoos.newrelic.plugins.inode_monitor"
    agent_version "1.0.1"
    agent_config_options :hostname
    agent_human_labels("Inode Agent") { "#{hostname}" }

    def poll_cycle        start = `df -i`.gsub('map ', 'map.')
        start = start.gsub('Mounted on', 'Mounted_On')
        result = {}
        disks = start.lines
        headers = disks.shift()
        headers = headers.split(/[ ]{1,}/)
        disks.each { |line|
            line = line.split(/[ ]{1,}/)
            mountedAt = line[headers.length-1].strip()

            mountedFrom = line[0].strip()
            result[mountedFrom] = {}
            i = 0
            headers.each { |header|
                header = header.gsub(/^%/, 'pct.').gsub(/%$/, '.pct').gsub(/%/, '.pct.').strip()
                result[mountedFrom][header] = line[i].strip().gsub('%', '')
                i += 1
            }
        }

        result.each { | disk, metric |
            metric.each { | k, v|
                report_metric("iNodes/#{disk}/#{k}",  "#{k}", v)
            }
        }


    end

  end

  NewRelic::Plugin::Setup.install_agent :inode, INodeAgent

  NewRelic::Plugin::Run.setup_and_run

end
