#! /usr/bin/env ruby

#
# This is an inode agent which monitors
# disk INode usage
#

require "rubygems"
require "bundler/setup"
require "newrelic_plugin"



        start = `df -i`.gsub('map ', 'map.')
        start = start.gsub('Mounted on', 'Mounted_On')
        result = {}
        disks = start.lines
        headers = disks.shift()
        headers = headers.split(/[ ]{1,}/)
        disks.each { |line|
            line = line.split(/[ ]{1,}/)
            mountedAt = line[headers.length-1].strip()

            mountedFrom = line[0].strip()
            result[mountedFrom] = {}
            i = 0
            headers.each { |header|
                header = header.gsub(/^%/, 'pct.').gsub(/%$/, '.pct').gsub(/%/, '.pct.').strip()
                result[mountedFrom][header] = line[i].strip().gsub('%', '')
                i += 1
            }
        }
        puts result.to_json
