#! /usr/bin/env ruby

#
# This is an inode agent which monitors
# disk INode usage
#

require "rubygems"
require "bundler/setup"
require "newrelic_plugin"


        start = `df -i`
        result = {}
        disks = start.lines
        headers = disks.shift()
        headers = headers.split(/[ ]{2,}|[ ][%]/)
        disks.each { |line|
            line = line.split(/[ ][0-9%]+/)
            mountedAt = line[7].strip()
            mountedFrom = line[0].strip()
            result[mountedFrom] = {}

            diskUsage = `df -i #{mountedAt}`.lines[1].gsub(mountedFrom, "").gsub('%', "").split(/[ ]{1,}/)
            i = 1
            headers.each { |header|
                result[mountedFrom][header] = diskUsage[i].strip()
                i += 1
            }
        }
puts result
